### ISSUE TITLE
[疑问]MultiTask

### ISSUE THREAD

**Issue by jp928** [swlib/archer#4]
在 MultiTask中，有些代码不太理解，希望能够得到解释，比如在yieldEachOne中
`       if (0 === $unfinished_task_count) {
            foreach ($this->result_map as $k => $v) {
                yield $k => $v;
            }
            return $this->result_map;
        }`

**Comment by fdreamsu** [comment]
`MultiTask`中`addTask`是将任务投递并立即执行，所以在执行`yieldEachOne`时会有三种情况
1、所有任务均以完成
2、部分完成
3、所有任务都没有完成

你发的代码就是对于`情况1`的特殊处理

**Comment by jp928** [comment]
@fdreamsu 
感谢您的回复。
如果我执行

`
foreach($multi_task->yieldEachOne() as $key => $value) {
}
`
那我是在迭代 yield $k => $v 还是在 循环 $this->result_map ?

**Comment by fdreamsu** [comment]
你要去看下[generator的定义](https://php.net/manual/zh/class.generator.php)  
使用`foreach`时是在对`yield $k => $v`进行迭代，而返回值`$this->result_map`是需要对返回值对象执行`getReturn()`方法获取的，即：
```php
$result = $multi_task->yieldEachOne();
foreach($result as $key => $value) {
    // 这里是对于yield进行迭代
}
var_dump($result->getReturn());//迭代结束后，可以通过该方法获取return的值
```
